version: '3'
services:

  web:
    build:
      context: ../flask_site
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      FLASK_ENV: development

  tests:
    command: pytest --executor browser --app_host http://web
    build:
      context: ../tests
      dockerfile: Dockerfile
    depends_on:
      - web
      - browser

  browser:
    image: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200921
    ports:
      - "4444:4444"
